# Tasca M3 T01

## Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [4]:
import numpy as np

Array= np.random.randint(0, 101, size=(100))
print(Array)

[ 58  34   2  34  77  15  24  72  25  48  77  45  90  60  78  81  86  16
  71  89  39  95  73  38  39  74  71  91  56  28  18  19  96   6  67  39
  83  98   2  52  65  28   2  19  50  23  62  54  18  97  85  90  85   1
   0  66  68  64  11  53  48  57  33  86  31  28  47  49  32  94  25  42
  51  87  30  54  28  83  37  22  64  37  77  32  88  29  80  30  58 100
  53  80  86  50  88  96  63  56  32  71]


In [5]:
def resum_stdtc(arr):
    if arr.ndim != 1:
        print("Error: l'array té més d'una dimensió")
    else:
        print("Resum estadístic:")
        print("Mínim: ", np.min(arr))
        print("Màxim: ", np.max(arr))
        print("Mitjana: ", np.mean(arr))
        print("Mediana: ", np.median(arr))
        print("Desviació estàndard: ", np.std(arr))
        print("Quartil 1: ", np.percentile(arr, 25))
        print("Quartil 3: ", np.percentile(arr, 75))

In [6]:
resum_stdtc(Array)

Resum estadístic:
Mínim:  0
Màxim:  100
Mitjana:  53.41
Mediana:  53.5
Desviació estàndard:  27.45690987711472
Quartil 1:  30.75
Quartil 3:  77.25


## Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [5]:
import numpy as np

def generar_matriu():
    matriu = np.random.randint(0, 101, size=(5, 5))
    return matriu

matriz = generar_matriu()
print(matriz)


[[49 75 80 52 88]
 [77 36 43 29 90]
 [70 62 98 88 48]
 [37 46 18 23 38]
 [19 13 98 75 97]]


## Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [4]:
def calcular_totals(matriz):
    sum_filas = np.sum(matriz, axis=1)
    sum_columnas = np.sum(matriz, axis=0)
    
    print("Suma de files:")
    for fila in sum_filas:
        print(fila)
    
    print("Suma de columnes:")
    for columna in sum_columnas:
        print(columna)

In [7]:
calcular_totals(matriz)

Suma de filas:
344
275
366
162
302
Suma de columnas:
252
232
337
267
361


## Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [12]:
import numpy as np
import scipy.stats

In [12]:
A = np.random.randint(1, 100, size=10)
B = np.random.randint(1, 100, size=10)
print(A,B)

[10 10  3 56  1 79  4 17 46  7] [15 32 20 28 88 38 41 66 88 71]


Sabem que les dades són numériques, a més sent que es un random randint podem assumir també la seva normalitat llavor l'adeqüat seria fer Pearsons

$$r_{xy} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2} \sqrt{\sum_{i=1}^{n}(y_i - \bar{y})^2}}$$

- **xi** i **yi** són els valors de la i-aquesta en els conjunts de dades 
- $\bar{x}$ i $\bar{y}$ són les mitjanes
- **n** és la quantitat d' observacions en els conjunts de dades.

    _Recordem que X correspondrà a la variable independent i la Y a la dependent, a més si es donen dos valors s'assumirà que el primer correspondrà a X i el segon a Y_

In [15]:
import numpy as np

def pearson(x, y):
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    std_x = np.std(x)
    std_y = np.std(y)
    cov_xy = np.cov(x, y)[0, 1]
    corr = cov_xy / (std_x * std_y)
    print("El coeficient de correlació és:", corr)
    
    if corr >= 0.7:
        print("Existeix una correlació positiva forta entre les dues variables")
    elif 0.3 <= corr < 0.7:
        print("Existeix una correlació positiva moderada entre les dues variables")
    elif 0.1 <= corr < 0.3:
        print("Existeix una correlació positiva feble entre les dues variables")
    elif -0.1 <= corr < 0.1:
        print("No hi ha correlació significativa entre les dues variables")
    elif -0.3 <= corr < -0.1:
        print("Existeix una correlació negativa feble entre les dues variables")
    elif -0.7 <= corr < -0.3:
        print("Existeix una correlació negativa moderada entre les dues variables")
    elif corr < -0.7:
        print("Existeix una correlació negativa forta entre les dues variables")
    else:
        print("El coeficient de correlació està fora de rang, ha ocurregut un error")
    
    return corr

In [16]:
pearson(A, B)

El coeficient de correlació és: -0.054599357850576645
No hi ha correlació significativa entre les dues variables


-0.054599357850576645